
name: Feature request
description: Sugestão de melhoria ou nova funcionalidade
labels: enhancement
body:
  - type: textarea
    id: proposal
    attributes:
      label: Descrição
      description: O que você gostaria de ver adicionado?
      placeholder: Explique a proposta...
    validations:
      required: true
